### ISSUE TITLE
Cloudformation for 'CloudWatch Events to Start a Pipeline'

### ISSUE THREAD

**Issue by LpmRaven** [awsdocs/aws-codepipeline-user-guide#30]
How do I [Use Amazon CloudWatch Events to Start a Pipeline on a Schedule](https://github.com/awsdocs/aws-codepipeline-user-guide/blob/704ef80083435739aa840102bac923e7be3d9208/doc_source/pipelines-trigger-source-schedule.md) via cloudformation?

I expected it to work like this, but I don't seem to be able to obtain the pipeline ARN. I can not find documentation relating to this.

```
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !GetAtt Pipeline.Arn
          Id: id-here

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    ...
```

**Comment by LpmRaven** [comment]
Not sure if this is correct but it successfully deployed. I need correcting on what permissions are needed for the eventRule and what is needed for the eventRule target role.

```
  EventRuleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: eventrule-codepipeline
          PolicyDocument:
            Statement:
              - Action:
                  - codepipeline:StartPipelineExecution
                  - codepipeline:StopPipelineExecution
                  - codepipeline:RetryStageExecution
                  - codepipeline:GetPipelineExecution
                Resource: !Join ["", [ !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:', !Ref Pipeline, "*"]]
                Effect: Allow

  EventRule:
    Type: AWS::Events::Rule
    Properties:
      RoleArn: !GetAtt EventRuleRole.Arn
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !Join ["", [ !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:', !Ref Pipeline]]
          Id: id-here
          RoleArn: !GetAtt EventRuleRole.Arn

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    ...
```

Also, why is this the only way to reference the codepipeline ARN? I spent an hour looking for a way to reference the ARN and found nothing. If there is a better way, please do let me know.
```
!Join ["", [ !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:', !Ref Pipeline]]
```
