### ISSUE TITLE
codestar-connections Action invalid in IAM with "unrecognized services"

### ISSUE THREAD

**Issue by Marakai** [awsdocs/aws-codepipeline-user-guide#34]
I have a CFN template creating a role to access Bitbucket Cloud as a CodeStar connection.

As per documentation (https://docs.aws.amazon.com/codepipeline/latest/userguide/connections-permissions.html) I have:

```
 - Effect: Allow
   Action:
       - 'codestar-connections:GetConnections'
       - 'codestar-connections:ListConnections'
       - 'codestar-connections:UseConnections'
       - 'codestar-connections:PassConnections'
    Resource: '*'
```

This fails, however and when I verify in IAM I see

```
Unrecognized services
codestar-connections
```

and accordingly, the permissions are not added to the policy.

As per 

https://docs.aws.amazon.com/codepipeline/latest/userguide/security-iam.html#how-to-update-role-new-services

support for AWS CodeStar Connections was added on December 18, 2019. I see no mention that would be limited or restricted (it's IAM, it should be global!).

The result is that I receive "not authorised" in the Source stage when trying to use the connection.

I've created a pipeline manually in the console, letting it create a new role - and here too I see that the role created gives errors about codestar-connections being unrecognized, resulting in authorisation failure.

Am I missing something?
